name: himorna-env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10.0
  - pandas=1.5.3
  - matplotlib=3.7.2
  - scipy=1.11.1
  - statsmodels=0.14.0
  - biopython=1.81
  - mygene=3.2.2
  - h5py=3.9.0
  - seaborn=0.12.2
  - ipykernel=6.25.1
